### ISSUE TITLE
Can't specify description, name, summary, version when publishing `raw` packages

### ISSUE THREAD

**Issue by tmccnnll** [cloudsmith-io/orb#14]
The current implementation of the `publish` command does not allow you to specify additional properties of `raw` packages being published. Specifically, I'm interested in being able to specify the package description, name, summary, and version. These are all available as options for the `cloudsmith push raw` command.

I've forked this repo and created a PR containing modifications to `src/commands/publish.yml` that would allow an end-user to specify the information I've mentioned: https://github.com/cloudsmith-io/orb/pull/13.

**Comment by paddycarey** [comment]
Hi @tmccnnll, your PR's been merged and the orb released https://circleci.com/developer/orbs/orb/cloudsmith/cloudsmith?version=1.0.5

Let me know if there are any issues!
