### ISSUE TITLE
package-type or package-format?

### ISSUE THREAD

**Issue by aidanlane** [cloudsmith-io/orb#4]
Hi, command-publish.yml refers to `package-type`, but should it be `package-format`?

Noticed it first here: https://circleci.com/orbs/registry/orb/cloudsmith/cloudsmith

Cheers!

**Comment by paddycarey** [comment]
Good catch, thanks! We'll fix asap.

**Comment by paddycarey** [comment]
Just pushed a fix for this, thanks!

**Comment by aidanlane** [comment]
Wow, that was quick, thanks!
